Mappings: 
  RegionMap: 
    us-east-1: 
      "AMI": "ami-0ff8a91507f77f867"
    us-west-1: 
      "AMI": "ami-0bdb828fd58c52235"
    eu-west-1: 
      "AMI": "ami-047bb4163c506cd98"
    ap-southeast-1: 
      "AMI": "ami-08569b978cc4dfa10"
    ap-northeast-1: 
      "AMI": "ami-06cd52961ce9f0d85"
Resources :
  MyInstnce:
     Type: AWS::EC2::Instance
      Properties:
      InstnceType: t2.micro
       ImageId: !findInMap
       Tags:
      - key: "Name"
       Value: !Join ["-", [my,inst,from,cloudformation]]
    SecurityGroup:
       - !Ref VprofileSG   

VprofilesG: 
   Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: Allow http to client host
    VpcId: Ref: myVPC
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
    SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0