Resources :
  MyInstnce:
     Type: AWS::EC2::Instance
      Properties:
         InstnceType: t2.micro
          ImageId: ami-o36392654074t
          Tags:
            -Key: "Name"
             Value: !Join  ["-",[my, form, cloudformation]]
           SecurityGroups:
              -!Ref VrofileSG  
  VrofileSG:
   Type: AWS::EC2::SecurityGroup
      Properties:
         GroupDescription: Allow http to client host
         VpcId: Ref: myVPC
         SecurityGroupIngress:
               - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  CidrIp: 0.0.0.0/0
         SecurityGroupEgress:
              - IpProtocol: tcp
               FromPort: 80
               ToPort: 80
               CidrIp: 0.0.0.0/0